language: android
android:
  components:
    - tools
    - build-tools-24.0.0
    - extra-android-support
    - extra-android-m2repository
    - android-24
  licenses:
    - 'android-sdk-license-.+'

jdk: oraclejdk8

sudo: false

before_install:
  - echo "bintray.user=dummy_user" > local.properties
  - echo "bintray.apikey=dummy_api_key" >> local.properties
  - echo "bintray.gpg.password=dummy_password" >> local.properties

script:
  - ./gradlew clean build